---
- name: Ensure nginx-ingress-controller directory
  file: path={{ ansible_env.HOME }}/addons/cinder-storage state=directory mode=0755

- name: Copy cinder storage config file
  copy:
    src: cinder-storage.yaml
    dest: "{{ ansible_env.HOME }}/addons/cinder-storage/cinder-storage.yaml"
    force: yes

- name: Apply default cinder storage
  shell: kubectl apply -f {{ ansible_env.HOME }}/addons/cinder-storage/cinder-storage.yaml
