---
ccm_image: "docker.io/k8scloudprovider/openstack-cloud-controller-manager:v1.17.0"
reource_prefix: "sbwa"

auth_url: http://192.168.121.15/identity/v3/
user_id: 037536f060594d60bdadaa71d060c17f
password: password
tenant_id: 7f2e98177ca848cf8465d7827d28b0d8
region: RegionOne
subnet_id: 4ebbb7fa-0a9f-4db3-9a0f-36e8c974a2a7
support_octavia: yes
